resources:
  - name: texter
    type: git
    source: 
      uri: https://github.com/jduv/201709-atlcodecamp-tddinfra.git
      branch: master

jobs:
  - name: build
    plan:
      - get: texter
        trigger: true
      - task: build
        file: texter/ci/tasks/build.yml