resources:
- name: texter
  type: git
  source: 
    uri: https://github.com/jduv/201710-anarchy-workshop.git
    branch: master
- name: release
  type: docker-image
  source:
    repository: 964357038409.dkr.ecr.us-east-1.amazonaws.com/7fprod

jobs:
- name: build
  plan:
  - get: texter
    trigger: true
  - task: build
    file: texter/ci/tasks/build.yml

- name: test
  plan:
  - get: texter
    trigger: true
  - task: test
    file: texter/ci/tasks/test.yml

- name: release
  plan:
  - get: texter
    trigger: true
  - put: release
    params: { build: texter }