version: '2'
services:
  texter:
    build: .
    env_file:
      - .env
    ports:
      - "${HOST_PORT}:${CONT_PORT}"
    links:
      - txt_mongo
  txt_mongo:
    image: mongo:3.4
    command: mongod --port ${MONGO_CONT_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGO_RRN_USER
      - MONGO_RRN_PASS
      - MONGO_RRN_DB
    ports:
      - "${MONGO_HOST_PORT}:${MONGO_CONT_PORT}"
    volumes: 
      - ./db/mongo:/docker-entrypoint-initdb.d/
      - /mnt/volume-sfo2-02/db/:/data/db